### ISSUE TITLE
Frontend dies if data source is updated

### ISSUE THREAD

**Issue by YngveMolnes** [it2901/Skrp#137]
Right now the frontend hardcodes the mocker. In our acceptance test, a requirements is being able to update the data source. This will cause problems for the frontend. If the original datasource goes offline, the frontend can't fetch new data from it. If the datasource is updated, but the original datasource stays online - the frontend wil proceed to ask the old datasource. This i bad bad behaviour. The fix for this, is to ask the /serverconfig endpoint of the backend for where the datasource is located. Update this where needed, and replace the hardcoding of datasource(mocker) with the response from /serverconfig.

**Comment by allmeta** [comment]
Not using the mocker anymore
