### ISSUE TITLE
No dynamic content is displayed in the virtual machine if accessing the machine by host machine IP rather than localhost

### ISSUE THREAD

**Issue by YngveMolnes** [it2901/Skrp#142]
From FFI:

> jeg kommer også til appen fra andre maskiner (ved å bruke ip fremfor localhost), med da er den uten innhold – altså ingen noder i grafen, ingen entires i logg etc).

**Comment by allmeta** [comment]
True. The data source on the frontend is static. Might be possible to use lan ip instead of localhost though?
